cl: 250

faults:
  - name: main
    trace: [[0, 0], [5000, 0], [10000, 800]]
    top_depth: 0.0
    bottom_depth: -6000.0
    dip: 80.0
    curve_type: spline

  - name: splay
    trace: [[10000, 800], [13000, 3000]]
    top_depth: 0.0
    bottom_depth: -3500.0
    dip: 55.0
    curve_type: polyline